name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test  